create database cinematicketshop;

use cinematicketshop;

CREATE TABLE Users(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Username VARCHAR(200) NOT NULL,
	Password VARCHAR(200) NOT NULL,
	Firstname VARCHAR(200) NOT NULL,
	Lastname VARCHAR(200) NOT NULL,
	Age INT NOT NULL,
	Email VARCHAR(200) NOT NULL
);

CREATE TABLE Cinemas(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Address VARCHAR(200) NOT NULL,
	Name VARCHAR(200) NOT NULL
);

CREATE TABLE Movies(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(200) NOT NULL,
	Cost INT NOT NULL,
	Genre VARCHAR(50) NOT NULL,
	AgeResctriction VARCHAR(50) NOT NULL,
	ScreenType VARCHAR(50) NOT NULL
);

CREATE TABLE ScreeningRooms(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CinemaID INT NOT NULL,
	FOREIGN KEY (CinemaID) REFERENCES Cinemas(ID)
);

CREATE TABLE Seats(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	RowNumber INT NOT NULL,
	SeatNumber INT NOT NULL,
	IsTaken BOOLEAN NOT NULL,
	ScreeningRoomID INT NOT NULL,
	FOREIGN KEY (ScreeningRoomID) REFERENCES ScreeningRooms(ID)
);

CREATE TABLE Shows(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ScreeningRoomID INT NOT NULL,
	MovieID INT NOT NULL,
	Date TIMESTAMP NOT NULL,
	FOREIGN KEY (ScreeningRoomID) REFERENCES ScreeningRooms(ID),
	FOREIGN KEY (MovieID) REFERENCES Movies(ID)
);

CREATE TABLE Tickets(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	UserID INT NOT NULL,
	ShowID INT NOT NULL,
	SeatID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(ID),
	FOREIGN KEY (ShowID) REFERENCES Shows(ID),
	FOREIGN KEY (SeatID) REFERENCES Seats(ID)
);
